spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Hrs12345
    url: jdbc:mysql://devops.hrs.cn:33061/testDatabase?characterEncoding=utf-8&useSSL=false
  jpa:
    ddl-auto: create
  jackson:
    default-property-inclusion: non_null
  redis:
    host: localhost
    port: 6379
    #password:
server:
  context-path: /
  port: 8088
#  context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#    com.imooc.LoggerTest: debug
wechat:
  # 微信授权 id
#  mpAppId: wx0465fe3767346d03
#  mpAppSecret: 98f3f91786611085871483c1b799aaf5
  mpAppId: wx6033c8845b4d393e
  mpAppSecret: 60458e21bb16c8b89bd7ea353ba43924
  openAppId: xxxxxxxxxxxxxxxxxx
  openAppSecret: xxxxxxxxxxxxxxxxxxxxx
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath:  C:/Users/Hasee/Desktop/SpringBoot_Wechat_Sell/src/main/resources/h5.p12
  notifyUrl: http://1m929o4661.imwork.net/notify
  templateId:
    orderStatus: kahmCfZjV-2jORZ4yFti9-69smaV3gQ1lFFCDKL_vjI
    payStatus: kahmCfZjV-2jORZ4yFti9-69smaV3gQ1lFFCDKL_vjI

projectUrl:
  wechatMpAuthorize: http://onlyoucd.free.ngrok.cc
  wechatOpenAuthorize: http://onlyoucd.free.ngrok.cc
  sell: http://localhost:8080
logging:
  level:
    com.ldlood.dataobject.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml





